export const domElements = {
    currentTrackElement: document.getElementById("current-track"),
    upcomingList: document.getElementById("upcoming-tracks"),
    trackName: document.getElementById("track-name"),
    duration: document.getElementById("duration"),
    audio: document.getElementById("audio-player"),
    playButton: document.getElementById("play"),
    prevButton: document.getElementById("prev"),
    nextButton: document.getElementById("next"),
    shuffleButton: document.getElementById("shuffle"),
    contextMenu: document.getElementById("context-menu"),
    addToQueueBtn: document.getElementById("add-to-front"),
    addToPlaylistBtn: document.getElementById("add-to-playlist"),
    deleteSongBtn: document.getElementById("delete-song"),
    playlistList: document.getElementById("playlist-list"),
    playlistContextMenu: document.getElementById("playlist-context-menu"),
    deletePlaylistBtn: document.getElementById("delete-playlist"),
    songSearch: document.getElementById("song-search"),
    playlistSearch: document.getElementById("playlist-search"),
    addSongBtn: document.getElementById("add-song-btn"),
    volumeSlider: document.getElementById("volume-slider"),
    seekSlider: document.getElementById("seek-slider"),
};